name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
  
      - name: Setup GO
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
    
      - name: build the app
        run: go build -o go-web-app
       
      - name: Test
        run: go test ./...
 
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Run golang lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1.6
  push:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
   
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: prod 
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{github.run_id}}
  
  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
    
      - name: Update tag in Helm chart
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'helm/go-web-app-chart/values.yaml'
          propertyPath: 'file.image.tag'
          value: '${{github.run_id}}'
          commitChange: false

      - name: Commit & push changes
        run: |
          git config --global user.name "HossainAhnaf"
          git config --global user.email "itsbuldusmp@gmail.com"
          git add helm/go-web-app-chart/values.yaml
          git commit -m "Update tag in helm chart"
          git push