name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'
  
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.5

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1.6
  
  push-image:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.event_name == 'push'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push to Dockerhub
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        target: prod
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{github.run_id}}

  sync-image-tag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: push-image

    steps:
      - uses: actions/checkout@v4
  
      - name: Update tag in Helm chart
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'helm/go-web-app-chart/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ github.run_id }}
          commitChange: true
          masterBranchName: main
