# name: Terraform CI pipeline
# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'infrastructure/**'
# 
#   pull_request:
#     branches:
#       - main
#     paths:
#       - 'infrastructure/**'
# 
# defaults:
#   run:
#     working-directory: infrastructure
# 
# jobs:
  

